version: 1.0.{build}
configuration:
- Debug
- Release
platform: x86
before_build:
- ps: .\Requirements.ps1
build:
  project: P4VS.sln
  verbosity: minimal
artifacts:
- path: HelixVS\bin\$(configuration)\P4VS.vsix
  name: P4VS.vsix
